[project]
name = "volatility-radar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "selenium>=4.41.0",
    "undetected-chromedriver>=3.5.5",
    "webdriver-manager>=4.0.2",
    "yfinance>=1.2.0",
]
